/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ContactForms: () => import('#controllers/contact_forms_controller'),
  client: {
    Clients: () => import('#controllers/client/clients_controller'),
    Commissions: () => import('#controllers/client/commissions_controller'),
  },
  admin: {
    Clients: () => import('#controllers/admin/clients_controller'),
    Commissions: () => import('#controllers/admin/commissions_controller'),
  },
}
