/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['clientUuid', 'createdAt', 'email', 'id', 'isVerified', 'name', 'password', 'updatedAt', 'username', 'verificationToken'] as const
  $columns = ClientSchema.$columns
  @column()
  declare clientUuid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean | null
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare verificationToken: string | null
}

export class CommissionSchema extends BaseModel {
  static $columns = ['clientUuid', 'commissionNumber', 'createdAt', 'idea', 'notes', 'refSheet', 'status', 'type', 'updatedAt'] as const
  $columns = CommissionSchema.$columns
  @column()
  declare clientUuid: string
  @column({ isPrimary: true })
  declare commissionNumber: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare idea: string
  @column()
  declare notes: string | null
  @column()
  declare refSheet: string
  @column()
  declare status: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
