/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClientSchema extends BaseModel {
  static $columns = ['clientUuid', 'createdAt', 'discord', 'email', 'id', 'name', 'password', 'tg', 'updatedAt'] as const
  $columns = ClientSchema.$columns
  @column()
  declare clientUuid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discord: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare tg: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommissionFormSchema extends BaseModel {
  static $columns = ['createdAt', 'discord', 'email', 'id', 'idea', 'name', 'notes', 'refSheet', 'status', 'tg', 'type', 'updatedAt'] as const
  $columns = CommissionFormSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discord: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idea: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare refSheet: string
  @column()
  declare status: string | null
  @column()
  declare tg: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommissionSchema extends BaseModel {
  static $columns = ['clientUuid', 'commissionNumber', 'createdAt', 'idea', 'notes', 'refSheet', 'status', 'type', 'updatedAt'] as const
  $columns = CommissionSchema.$columns
  @column()
  declare clientUuid: string
  @column({ isPrimary: true })
  declare commissionNumber: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare idea: string
  @column()
  declare notes: string | null
  @column()
  declare refSheet: string
  @column()
  declare status: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
