/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CommissionFormRouteImport } from './routes/commission/form'
import { Route as CommissionPricesRouteImport } from './routes/commission/prices'
import { Route as CommissionQueueRouteImport } from './routes/commission/queue'
import { Route as CommissionTosRouteImport } from './routes/commission/tos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionFormRoute = CommissionFormRouteImport.update({
  id: '/commission/form',
  path: '/commission/form',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionPricesRoute = CommissionPricesRouteImport.update({
  id: '/commission/prices',
  path: '/commission/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionQueueRoute = CommissionQueueRouteImport.update({
  id: '/commission/queue',
  path: '/commission/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionTosRoute = CommissionTosRouteImport.update({
  id: '/commission/tos',
  path: '/commission/tos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/commission/form': typeof CommissionFormRoute
  '/commission/prices': typeof CommissionPricesRoute
  '/commission/queue': typeof CommissionQueueRoute
  '/commission/tos': typeof CommissionTosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/commission/form': typeof CommissionFormRoute
  '/commission/prices': typeof CommissionPricesRoute
  '/commission/queue': typeof CommissionQueueRoute
  '/commission/tos': typeof CommissionTosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/commission/form': typeof CommissionFormRoute
  '/commission/prices': typeof CommissionPricesRoute
  '/commission/queue': typeof CommissionQueueRoute
  '/commission/tos': typeof CommissionTosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gallery'
    | '/commission/form'
    | '/commission/prices'
    | '/commission/queue'
    | '/commission/tos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/commission/form'
    | '/commission/prices'
    | '/commission/queue'
    | '/commission/tos'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gallery'
    | '/commission/form'
    | '/commission/prices'
    | '/commission/queue'
    | '/commission/tos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  CommissionFormRoute: typeof CommissionFormRoute
  CommissionPricesRoute: typeof CommissionPricesRoute
  CommissionQueueRoute: typeof CommissionQueueRoute
  CommissionTosRoute: typeof CommissionTosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission/form': {
      id: '/commission/form'
      path: '/commission/form'
      fullPath: '/commission/form'
      preLoaderRoute: typeof CommissionFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission/prices': {
      id: '/commission/prices'
      path: '/commission/prices'
      fullPath: '/commission/prices'
      preLoaderRoute: typeof CommissionPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission/queue': {
      id: '/commission/queue'
      path: '/commission/queue'
      fullPath: '/commission/queue'
      preLoaderRoute: typeof CommissionQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission/tos': {
      id: '/commission/tos'
      path: '/commission/tos'
      fullPath: '/commission/tos'
      preLoaderRoute: typeof CommissionTosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  CommissionFormRoute: CommissionFormRoute,
  CommissionPricesRoute: CommissionPricesRoute,
  CommissionQueueRoute: CommissionQueueRoute,
  CommissionTosRoute: CommissionTosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
